redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 4040:4040
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=4040
  command:
    sh -c 'npm i && node server.js'

