redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 4444:4444
  tty: true
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=test
    - PORT=4444
  command:
    sh -c 'npm i && npm run docker-mocha'